// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	adminauth "PowerX/internal/handler/admin/auth"
	admincommon "PowerX/internal/handler/admin/common"
	admincrmbusinessopportunity "PowerX/internal/handler/admin/crm/business/opportunity"
	admincrmcustomerDomaincustomer "PowerX/internal/handler/admin/crm/customerDomain/customer"
	admincrmcustomerDomainleader "PowerX/internal/handler/admin/crm/customerDomain/leader"
	admincrmcustomerDomainregisterCode "PowerX/internal/handler/admin/crm/customerDomain/registerCode"
	admincrmmarketmedia "PowerX/internal/handler/admin/crm/market/media"
	admincrmmarketmgm "PowerX/internal/handler/admin/crm/market/mgm"
	admincrmmarketstore "PowerX/internal/handler/admin/crm/market/store"
	admincrmmembership "PowerX/internal/handler/admin/crm/membership"
	admincrmproduct "PowerX/internal/handler/admin/crm/product"
	admincrmproductartisan "PowerX/internal/handler/admin/crm/product/artisan"
	admincrmproductcategory "PowerX/internal/handler/admin/crm/product/category"
	admincrmproductpricebook "PowerX/internal/handler/admin/crm/product/pricebook"
	admincrmproductpricebookentry "PowerX/internal/handler/admin/crm/product/pricebookentry"
	admincrmproductproductspecific "PowerX/internal/handler/admin/crm/product/productspecific"
	admincrmproductproductstatistics "PowerX/internal/handler/admin/crm/product/productstatistics"
	admincrmproductsku "PowerX/internal/handler/admin/crm/product/sku"
	admincrmtradeaddressbilling "PowerX/internal/handler/admin/crm/trade/address/billing"
	admincrmtradeaddressdelivery "PowerX/internal/handler/admin/crm/trade/address/delivery"
	admincrmtradeaddressshipping "PowerX/internal/handler/admin/crm/trade/address/shipping"
	admincrmtradeorder "PowerX/internal/handler/admin/crm/trade/order"
	admincrmtradepayment "PowerX/internal/handler/admin/crm/trade/payment"
	admincrmtradetoken "PowerX/internal/handler/admin/crm/trade/token"
	admindepartment "PowerX/internal/handler/admin/department"
	admindictionary "PowerX/internal/handler/admin/dictionary"
	admininfoOrganizationcategory "PowerX/internal/handler/admin/infoOrganization/category"
	adminmediaResource "PowerX/internal/handler/admin/mediaResource"
	adminpermission "PowerX/internal/handler/admin/permission"
	adminposition "PowerX/internal/handler/admin/position"
	adminscrmwechatofficialAccountmedia "PowerX/internal/handler/admin/scrm/wechat/officialAccount/media"
	adminscrmwechatofficialAccountmenu "PowerX/internal/handler/admin/scrm/wechat/officialAccount/menu"
	adminscrmwechatwecomapp "PowerX/internal/handler/admin/scrm/wechat/wecom/app"
	adminscrmwechatwecombot "PowerX/internal/handler/admin/scrm/wechat/wecom/bot"
	adminscrmwechatwecomcontractway "PowerX/internal/handler/admin/scrm/wechat/wecom/contractway"
	adminscrmwechatwecomcustomer "PowerX/internal/handler/admin/scrm/wechat/wecom/customer"
	adminscrmwechatwecomorganization "PowerX/internal/handler/admin/scrm/wechat/wecom/organization"
	adminscrmwechatwecomqrcode "PowerX/internal/handler/admin/scrm/wechat/wecom/qrcode"
	adminscrmwechatwecomresource "PowerX/internal/handler/admin/scrm/wechat/wecom/resource"
	adminscrmwechatwecomtag "PowerX/internal/handler/admin/scrm/wechat/wecom/tag"
	admintag "PowerX/internal/handler/admin/tag"
	adminuser "PowerX/internal/handler/admin/user"
	adminuserinfo "PowerX/internal/handler/admin/userinfo"
	mpcrmcustomer "PowerX/internal/handler/mp/crm/customer"
	mpcrmcustomerauth "PowerX/internal/handler/mp/crm/customer/auth"
	mpcrmmarketmedia "PowerX/internal/handler/mp/crm/market/media"
	mpcrmmarketstore "PowerX/internal/handler/mp/crm/market/store"
	mpcrmmembership "PowerX/internal/handler/mp/crm/membership"
	mpcrmproduct "PowerX/internal/handler/mp/crm/product"
	mpcrmproductartisan "PowerX/internal/handler/mp/crm/product/artisan"
	mpcrmproductproductstatistics "PowerX/internal/handler/mp/crm/product/productstatistics"
	mpcrmtradeaddressbilling "PowerX/internal/handler/mp/crm/trade/address/billing"
	mpcrmtradeaddressdelivery "PowerX/internal/handler/mp/crm/trade/address/delivery"
	mpcrmtradeaddressshipping "PowerX/internal/handler/mp/crm/trade/address/shipping"
	mpcrmtradecart "PowerX/internal/handler/mp/crm/trade/cart"
	mpcrmtradeorder "PowerX/internal/handler/mp/crm/trade/order"
	mpcrmtradepayment "PowerX/internal/handler/mp/crm/trade/payment"
	mpcrmtradetoken "PowerX/internal/handler/mp/crm/trade/token"
	mpdictionary "PowerX/internal/handler/mp/dictionary"
	mpinfoOrganizationcategory "PowerX/internal/handler/mp/infoOrganization/category"
	openapi "PowerX/internal/handler/openapi"
	openapiauth "PowerX/internal/handler/openapi/auth"
	openapiproviderbrainx "PowerX/internal/handler/openapi/provider/brainx"
	plugin "PowerX/internal/handler/plugin"
	systemhealth "PowerX/internal/handler/system/health"
	webaichatBot "PowerX/internal/handler/web/ai/chatBot"
	webcustomerauth "PowerX/internal/handler/web/customer/auth"
	webcustomerauthoa "PowerX/internal/handler/web/customer/auth/oa"
	webinfoOrganizationcategory "PowerX/internal/handler/web/infoOrganization/category"
	webscene "PowerX/internal/handler/web/scene"
	"PowerX/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 根目录访问
				Method:  http.MethodGet,
				Path:    "/",
				Handler: GetHomeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/access/actions/basic-login",
				Handler: adminauth.LoginHandler(serverCtx),
			},
			{
				// Exchange
				Method:  http.MethodPost,
				Path:    "/access/actions/exchange-token",
				Handler: adminauth.ExchangeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserNoPermJWTAuth},
			[]rest.Route{
				{
					// 通用获取Options
					Method:  http.MethodGet,
					Path:    "/options",
					Handler: admincommon.GetOptionsHandler(serverCtx),
				},
				{
					// 部门Options远程搜索
					Method:  http.MethodGet,
					Path:    "/options/departments",
					Handler: admincommon.GetDepartmentOptionsHandler(serverCtx),
				},
				{
					// 查询员工过滤条件
					Method:  http.MethodGet,
					Path:    "/options/user-query",
					Handler: admincommon.GetUserQueryOptionsHandler(serverCtx),
				},
				{
					// 员工Options远程搜索
					Method:  http.MethodGet,
					Path:    "/options/users",
					Handler: admincommon.GetUserOptionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/common"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 查询商机列表
					Method:  http.MethodGet,
					Path:    "/opportunities",
					Handler: admincrmbusinessopportunity.GetOpportunityListHandler(serverCtx),
				},
				{
					// 创建商机
					Method:  http.MethodPost,
					Path:    "/opportunities",
					Handler: admincrmbusinessopportunity.CreateOpportunityHandler(serverCtx),
				},
				{
					// 修改商机信息
					Method:  http.MethodPut,
					Path:    "/opportunities/:id",
					Handler: admincrmbusinessopportunity.UpdateOpportunityHandler(serverCtx),
				},
				{
					// 删除商机
					Method:  http.MethodDelete,
					Path:    "/opportunities/:id",
					Handler: admincrmbusinessopportunity.DeleteOpportunityHandler(serverCtx),
				},
				{
					// 为商机分配员工
					Method:  http.MethodPut,
					Path:    "/opportunities/:id/assign-user",
					Handler: admincrmbusinessopportunity.AssignUserToOpportunityHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/business"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建客户
					Method:  http.MethodPost,
					Path:    "/customers",
					Handler: admincrmcustomerDomaincustomer.CreateCustomerHandler(serverCtx),
				},
				{
					// 查询客户
					Method:  http.MethodGet,
					Path:    "/customers/:id",
					Handler: admincrmcustomerDomaincustomer.GetCustomerHandler(serverCtx),
				},
				{
					// 全量客户
					Method:  http.MethodPut,
					Path:    "/customers/:id",
					Handler: admincrmcustomerDomaincustomer.PutCustomerHandler(serverCtx),
				},
				{
					// 增量客户
					Method:  http.MethodPatch,
					Path:    "/customers/:id",
					Handler: admincrmcustomerDomaincustomer.PatchCustomerHandler(serverCtx),
				},
				{
					// 删除客户
					Method:  http.MethodDelete,
					Path:    "/customers/:id",
					Handler: admincrmcustomerDomaincustomer.DeleteCustomerHandler(serverCtx),
				},
				{
					// 为客户分配员工
					Method:  http.MethodPost,
					Path:    "/customers/:id/actions/users",
					Handler: admincrmcustomerDomaincustomer.AssignCustomerToUserHandler(serverCtx),
				},
				{
					// 获取客户分页列表
					Method:  http.MethodGet,
					Path:    "/customers/page-list",
					Handler: admincrmcustomerDomaincustomer.ListCustomersPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/customer-domain"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建线索
					Method:  http.MethodPost,
					Path:    "/leads",
					Handler: admincrmcustomerDomainleader.CreateLeadHandler(serverCtx),
				},
				{
					// 查询线索
					Method:  http.MethodGet,
					Path:    "/leads/:id",
					Handler: admincrmcustomerDomainleader.GetLeadHandler(serverCtx),
				},
				{
					// 全量线索
					Method:  http.MethodPut,
					Path:    "/leads/:id",
					Handler: admincrmcustomerDomainleader.PutLeadHandler(serverCtx),
				},
				{
					// 增量线索
					Method:  http.MethodPatch,
					Path:    "/leads/:id",
					Handler: admincrmcustomerDomainleader.PatchLeadHandler(serverCtx),
				},
				{
					// 删除线索
					Method:  http.MethodDelete,
					Path:    "/leads/:id",
					Handler: admincrmcustomerDomainleader.DeleteLeadHandler(serverCtx),
				},
				{
					// 为线索分配员工
					Method:  http.MethodPost,
					Path:    "/leads/:id/actions/users",
					Handler: admincrmcustomerDomainleader.AssignLeadToUserHandler(serverCtx),
				},
				{
					// 获取线索分页列表
					Method:  http.MethodGet,
					Path:    "/leads/page-list",
					Handler: admincrmcustomerDomainleader.ListLeadsPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/customer-domain"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建注册码
					Method:  http.MethodPost,
					Path:    "/register-codes",
					Handler: admincrmcustomerDomainregisterCode.CreateRegisterCodeHandler(serverCtx),
				},
				{
					// 查询注册码
					Method:  http.MethodGet,
					Path:    "/register-codes/:id",
					Handler: admincrmcustomerDomainregisterCode.GetRegisterCodeHandler(serverCtx),
				},
				{
					// 全量注册码
					Method:  http.MethodPut,
					Path:    "/register-codes/:id",
					Handler: admincrmcustomerDomainregisterCode.PutRegisterCodeHandler(serverCtx),
				},
				{
					// 增量注册码
					Method:  http.MethodPatch,
					Path:    "/register-codes/:id",
					Handler: admincrmcustomerDomainregisterCode.PatchRegisterCodeHandler(serverCtx),
				},
				{
					// 删除注册码
					Method:  http.MethodDelete,
					Path:    "/register-codes/:id",
					Handler: admincrmcustomerDomainregisterCode.DeleteRegisterCodeHandler(serverCtx),
				},
				{
					// 批量创建注册码
					Method:  http.MethodPost,
					Path:    "/register-codes/generate",
					Handler: admincrmcustomerDomainregisterCode.GenerateRegisterCodeHandler(serverCtx),
				},
				{
					// 获取注册码分页列表
					Method:  http.MethodGet,
					Path:    "/register-codes/page-list",
					Handler: admincrmcustomerDomainregisterCode.ListRegisterCodesPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/customer-domain"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 请求媒体上传链接
					Method:  http.MethodPost,
					Path:    "/medias",
					Handler: admincrmmarketmedia.CreateMediaHandler(serverCtx),
				},
				{
					// 创建或更新媒体
					Method:  http.MethodPut,
					Path:    "/medias/:id",
					Handler: admincrmmarketmedia.UpdateMediaHandler(serverCtx),
				},
				{
					// 根据媒体key获取媒体
					Method:  http.MethodGet,
					Path:    "/medias/:id",
					Handler: admincrmmarketmedia.GetMediaHandler(serverCtx),
				},
				{
					// 删除媒体
					Method:  http.MethodDelete,
					Path:    "/medias/:id",
					Handler: admincrmmarketmedia.DeleteMediaHandler(serverCtx),
				},
				{
					// 查询媒体列表
					Method:  http.MethodGet,
					Path:    "/medias/page-list",
					Handler: admincrmmarketmedia.ListMediasPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/market"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 请求MGMRule上传链接
					Method:  http.MethodPost,
					Path:    "/mgms",
					Handler: admincrmmarketmgm.CreateMGMRuleHandler(serverCtx),
				},
				{
					// 创建或更新MGMRule
					Method:  http.MethodPut,
					Path:    "/mgms/:id",
					Handler: admincrmmarketmgm.UpdateMGMRuleHandler(serverCtx),
				},
				{
					// 根据获取MGMRule
					Method:  http.MethodGet,
					Path:    "/mgms/:id",
					Handler: admincrmmarketmgm.GetMGMRuleHandler(serverCtx),
				},
				{
					// 删除MGMRule
					Method:  http.MethodDelete,
					Path:    "/mgms/:id",
					Handler: admincrmmarketmgm.DeleteMGMRuleHandler(serverCtx),
				},
				{
					// 查询MGMRule列表
					Method:  http.MethodGet,
					Path:    "/mgms/page-list",
					Handler: admincrmmarketmgm.ListMGMRulesPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/market"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建门店
					Method:  http.MethodPost,
					Path:    "/stores",
					Handler: admincrmmarketstore.CreateStoreHandler(serverCtx),
				},
				{
					// 查询门店详情
					Method:  http.MethodGet,
					Path:    "/stores/:id",
					Handler: admincrmmarketstore.GetStoreHandler(serverCtx),
				},
				{
					// 全量门店
					Method:  http.MethodPut,
					Path:    "/stores/:id",
					Handler: admincrmmarketstore.PutStoreHandler(serverCtx),
				},
				{
					// 删除门店
					Method:  http.MethodDelete,
					Path:    "/stores/:id",
					Handler: admincrmmarketstore.DeleteStoreHandler(serverCtx),
				},
				{
					// 分配门店经理给门店
					Method:  http.MethodPost,
					Path:    "/stores/:id/actions/assign-to-store-categroy",
					Handler: admincrmmarketstore.AssignStoreToStoreManagerHandler(serverCtx),
				},
				{
					// 查询门店列表
					Method:  http.MethodGet,
					Path:    "/stores/page-list",
					Handler: admincrmmarketstore.ListStoresPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/market"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 查询会籍
					Method:  http.MethodGet,
					Path:    "/customers/:id",
					Handler: admincrmmembership.GetCustomerHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/membership"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建产品
					Method:  http.MethodPost,
					Path:    "/products",
					Handler: admincrmproduct.CreateProductHandler(serverCtx),
				},
				{
					// 查询产品详情
					Method:  http.MethodGet,
					Path:    "/products/:id",
					Handler: admincrmproduct.GetProductHandler(serverCtx),
				},
				{
					// 全量产品
					Method:  http.MethodPut,
					Path:    "/products/:id",
					Handler: admincrmproduct.PutProductHandler(serverCtx),
				},
				{
					// 增量产品
					Method:  http.MethodPatch,
					Path:    "/products/:id",
					Handler: admincrmproduct.PatchProductHandler(serverCtx),
				},
				{
					// 删除产品
					Method:  http.MethodDelete,
					Path:    "/products/:id",
					Handler: admincrmproduct.DeleteProductHandler(serverCtx),
				},
				{
					// 分配产品品类给产品品类分类
					Method:  http.MethodPost,
					Path:    "/products/:id/actions/assign-to-product-categroy",
					Handler: admincrmproduct.AssignProductToProductCategoryHandler(serverCtx),
				},
				{
					// 下架产品
					Method:  http.MethodPut,
					Path:    "/products/disable/:id",
					Handler: admincrmproduct.DisableProductHandler(serverCtx),
				},
				{
					// 查询产品列表
					Method:  http.MethodGet,
					Path:    "/products/page-list",
					Handler: admincrmproduct.ListProductsPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建元匠
					Method:  http.MethodPost,
					Path:    "/artisans",
					Handler: admincrmproductartisan.CreateArtisanHandler(serverCtx),
				},
				{
					// 查询元匠详情
					Method:  http.MethodGet,
					Path:    "/artisans/:id",
					Handler: admincrmproductartisan.GetArtisanHandler(serverCtx),
				},
				{
					// 全量元匠
					Method:  http.MethodPut,
					Path:    "/artisans/:id",
					Handler: admincrmproductartisan.PutArtisanHandler(serverCtx),
				},
				{
					// 删除元匠
					Method:  http.MethodDelete,
					Path:    "/artisans/:id",
					Handler: admincrmproductartisan.DeleteArtisanHandler(serverCtx),
				},
				{
					// 元匠绑定门店
					Method:  http.MethodPost,
					Path:    "/artisans/bind/stores",
					Handler: admincrmproductartisan.BindArtisanToStoreHandler(serverCtx),
				},
				{
					// 查询元匠列表
					Method:  http.MethodGet,
					Path:    "/artisans/page-list",
					Handler: admincrmproductartisan.ListArtisansPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创新产品品类
					Method:  http.MethodPost,
					Path:    "/product-categories",
					Handler: admincrmproductcategory.CreateProductCategoryHandler(serverCtx),
				},
				{
					// 查询产品品类详情
					Method:  http.MethodGet,
					Path:    "/product-categories/:id",
					Handler: admincrmproductcategory.GetProductCategoryHandler(serverCtx),
				},
				{
					// 修改产品品类
					Method:  http.MethodPut,
					Path:    "/product-categories/:id",
					Handler: admincrmproductcategory.UpdateProductCategoryHandler(serverCtx),
				},
				{
					// 修改产品品类父级
					Method:  http.MethodPatch,
					Path:    "/product-categories/:id",
					Handler: admincrmproductcategory.PatchProductCategoryHandler(serverCtx),
				},
				{
					// 删除产品品类
					Method:  http.MethodDelete,
					Path:    "/product-categories/:id",
					Handler: admincrmproductcategory.DeleteProductCategoryHandler(serverCtx),
				},
				{
					// 查询产品品类列表
					Method:  http.MethodGet,
					Path:    "/product-category-tree",
					Handler: admincrmproductcategory.ListProductCategoryTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创新价格手册
					Method:  http.MethodPost,
					Path:    "/price-books",
					Handler: admincrmproductpricebook.UpsertPriceBookHandler(serverCtx),
				},
				{
					// 查询价格手册详情
					Method:  http.MethodGet,
					Path:    "/price-books/:id",
					Handler: admincrmproductpricebook.GetPriceBookHandler(serverCtx),
				},
				{
					// 删除价格手册
					Method:  http.MethodDelete,
					Path:    "/price-books/:id",
					Handler: admincrmproductpricebook.DeletePriceBookHandler(serverCtx),
				},
				{
					// 查询价格手册列表
					Method:  http.MethodGet,
					Path:    "/price-books/page-list",
					Handler: admincrmproductpricebook.ListPriceBooksHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 查询价格手册条目详情
					Method:  http.MethodGet,
					Path:    "/price-book-entries/:id",
					Handler: admincrmproductpricebookentry.GetPriceBookEntryHandler(serverCtx),
				},
				{
					// 配置价格手册条目条目
					Method:  http.MethodPost,
					Path:    "/price-book-entries/:id",
					Handler: admincrmproductpricebookentry.UpdatePriceBookEntryHandler(serverCtx),
				},
				{
					// 删除价格手册条目
					Method:  http.MethodDelete,
					Path:    "/price-book-entries/:id",
					Handler: admincrmproductpricebookentry.DeletePriceBookEntryHandler(serverCtx),
				},
				{
					// 配置价格手册条目条目
					Method:  http.MethodPost,
					Path:    "/price-book-entries/config",
					Handler: admincrmproductpricebookentry.ConfigPriceBookEntryHandler(serverCtx),
				},
				{
					// 查询价格手册条目列表
					Method:  http.MethodGet,
					Path:    "/price-book-entries/page-list",
					Handler: admincrmproductpricebookentry.ListPriceBookEntriesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建产品规格
					Method:  http.MethodPost,
					Path:    "/product-specifics",
					Handler: admincrmproductproductspecific.CreateProductSpecificHandler(serverCtx),
				},
				{
					// 查询产品规格详情
					Method:  http.MethodGet,
					Path:    "/product-specifics/:id",
					Handler: admincrmproductproductspecific.GetProductSpecificHandler(serverCtx),
				},
				{
					// 全量产品规格
					Method:  http.MethodPut,
					Path:    "/product-specifics/:id",
					Handler: admincrmproductproductspecific.PutProductSpecificHandler(serverCtx),
				},
				{
					// 增量产品规格
					Method:  http.MethodPatch,
					Path:    "/product-specifics/:id",
					Handler: admincrmproductproductspecific.PatchProductSpecificHandler(serverCtx),
				},
				{
					// 删除产品规格
					Method:  http.MethodDelete,
					Path:    "/product-specifics/:id",
					Handler: admincrmproductproductspecific.DeleteProductSpecificHandler(serverCtx),
				},
				{
					// 配置产品规格
					Method:  http.MethodPost,
					Path:    "/product-specifics/config",
					Handler: admincrmproductproductspecific.ConfigProductSpecificHandler(serverCtx),
				},
				{
					// 查询产品规格列表
					Method:  http.MethodGet,
					Path:    "/product-specifics/page-list",
					Handler: admincrmproductproductspecific.ListProductSpecificPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 查询产品统计详情
					Method:  http.MethodGet,
					Path:    "/product-statistics/:id",
					Handler: admincrmproductproductstatistics.GetProductStatisticsHandler(serverCtx),
				},
				{
					// 全量产品统计
					Method:  http.MethodPut,
					Path:    "/product-statistics/:id",
					Handler: admincrmproductproductstatistics.PutProductStatisticsHandler(serverCtx),
				},
				{
					// 增量产品统计
					Method:  http.MethodPatch,
					Path:    "/product-statistics/:id",
					Handler: admincrmproductproductstatistics.PatchProductStatisticsHandler(serverCtx),
				},
				{
					// 配置产品统计
					Method:  http.MethodPost,
					Path:    "/product-statistics/config",
					Handler: admincrmproductproductstatistics.ConfigProductStatisticsHandler(serverCtx),
				},
				{
					// 查询产品统计列表
					Method:  http.MethodGet,
					Path:    "/product-statistics/page-list",
					Handler: admincrmproductproductstatistics.ListProductStatisticsPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建SKU
					Method:  http.MethodPost,
					Path:    "/skus",
					Handler: admincrmproductsku.CreateSKUHandler(serverCtx),
				},
				{
					// 查询SKU详情
					Method:  http.MethodGet,
					Path:    "/skus/:id",
					Handler: admincrmproductsku.GetSKUHandler(serverCtx),
				},
				{
					// 全量SKU
					Method:  http.MethodPut,
					Path:    "/skus/:id",
					Handler: admincrmproductsku.PutSKUHandler(serverCtx),
				},
				{
					// 增量SKU
					Method:  http.MethodPatch,
					Path:    "/skus/:id",
					Handler: admincrmproductsku.PatchSKUHandler(serverCtx),
				},
				{
					// 删除SKU
					Method:  http.MethodDelete,
					Path:    "/skus/:id",
					Handler: admincrmproductsku.DeleteSKUHandler(serverCtx),
				},
				{
					// 配置SKU
					Method:  http.MethodPost,
					Path:    "/skus/config",
					Handler: admincrmproductsku.ConfigSKUHandler(serverCtx),
				},
				{
					// 查询SKU列表
					Method:  http.MethodGet,
					Path:    "/skus/page-list",
					Handler: admincrmproductsku.ListSKUPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建账单地址
					Method:  http.MethodPost,
					Path:    "/billing",
					Handler: admincrmtradeaddressbilling.CreateBillingAddressHandler(serverCtx),
				},
				{
					// 查询账单地址详情
					Method:  http.MethodGet,
					Path:    "/billing/:id",
					Handler: admincrmtradeaddressbilling.GetBillingAddressHandler(serverCtx),
				},
				{
					// 更新账单地址
					Method:  http.MethodPut,
					Path:    "/billing/:id",
					Handler: admincrmtradeaddressbilling.PutBillingAddressHandler(serverCtx),
				},
				{
					// 部分更新账单地址
					Method:  http.MethodPatch,
					Path:    "/billing/:id",
					Handler: admincrmtradeaddressbilling.PatchBillingAddressHandler(serverCtx),
				},
				{
					// 删除账单地址
					Method:  http.MethodDelete,
					Path:    "/billing/:id",
					Handler: admincrmtradeaddressbilling.DeleteBillingAddressHandler(serverCtx),
				},
				{
					// 查询账单地址列表
					Method:  http.MethodGet,
					Path:    "/billing/page-list",
					Handler: admincrmtradeaddressbilling.ListBillingAddressesPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建订单发货地址
					Method:  http.MethodPost,
					Path:    "/delivery",
					Handler: admincrmtradeaddressdelivery.CreateDeliveryAddressHandler(serverCtx),
				},
				{
					// 查询订单发货地址详情
					Method:  http.MethodGet,
					Path:    "/delivery/:id",
					Handler: admincrmtradeaddressdelivery.GetDeliveryAddressHandler(serverCtx),
				},
				{
					// 更新订单发货地址
					Method:  http.MethodPut,
					Path:    "/delivery/:id",
					Handler: admincrmtradeaddressdelivery.PutDeliveryAddressHandler(serverCtx),
				},
				{
					// 部分更新订单发货地址
					Method:  http.MethodPatch,
					Path:    "/delivery/:id",
					Handler: admincrmtradeaddressdelivery.PatchDeliveryAddressHandler(serverCtx),
				},
				{
					// 删除订单发货地址
					Method:  http.MethodDelete,
					Path:    "/delivery/:id",
					Handler: admincrmtradeaddressdelivery.DeleteDeliveryAddressHandler(serverCtx),
				},
				{
					// 查询订单发货地址列表
					Method:  http.MethodGet,
					Path:    "/delivery/page-list",
					Handler: admincrmtradeaddressdelivery.ListDeliveryAddressesPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建收货地址
					Method:  http.MethodPost,
					Path:    "/shipping",
					Handler: admincrmtradeaddressshipping.CreateShippingAddressHandler(serverCtx),
				},
				{
					// 查询收货地址详情
					Method:  http.MethodGet,
					Path:    "/shipping/:id",
					Handler: admincrmtradeaddressshipping.GetShippingAddressHandler(serverCtx),
				},
				{
					// 更新收货地址
					Method:  http.MethodPut,
					Path:    "/shipping/:id",
					Handler: admincrmtradeaddressshipping.PutShippingAddressHandler(serverCtx),
				},
				{
					// 部分更新收货地址
					Method:  http.MethodPatch,
					Path:    "/shipping/:id",
					Handler: admincrmtradeaddressshipping.PatchShippingAddressHandler(serverCtx),
				},
				{
					// 删除收货地址
					Method:  http.MethodDelete,
					Path:    "/shipping/:id",
					Handler: admincrmtradeaddressshipping.DeleteShippingAddressHandler(serverCtx),
				},
				{
					// 查询收货地址列表
					Method:  http.MethodGet,
					Path:    "/shipping/page-list",
					Handler: admincrmtradeaddressshipping.ListShippingAddressesPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建订单
					Method:  http.MethodPost,
					Path:    "/orders",
					Handler: admincrmtradeorder.CreateOrderHandler(serverCtx),
				},
				{
					// 查询订单详情
					Method:  http.MethodGet,
					Path:    "/orders/:id",
					Handler: admincrmtradeorder.GetOrderHandler(serverCtx),
				},
				{
					// 更新订单
					Method:  http.MethodPut,
					Path:    "/orders/:id",
					Handler: admincrmtradeorder.PutOrderHandler(serverCtx),
				},
				{
					// 部分更新订单
					Method:  http.MethodPatch,
					Path:    "/orders/:id",
					Handler: admincrmtradeorder.PatchOrderHandler(serverCtx),
				},
				{
					// 删除订单
					Method:  http.MethodDelete,
					Path:    "/orders/:id",
					Handler: admincrmtradeorder.DeleteOrderHandler(serverCtx),
				},
				{
					// 导出订单
					Method:  http.MethodGet,
					Path:    "/orders/export",
					Handler: admincrmtradeorder.ExportOrdersHandler(serverCtx),
				},
				{
					// 导入订单
					Method:  http.MethodPost,
					Path:    "/orders/import",
					Handler: admincrmtradeorder.ImportOrdersHandler(serverCtx),
				},
				{
					// 查询订单列表
					Method:  http.MethodGet,
					Path:    "/orders/page-list",
					Handler: admincrmtradeorder.ListOrdersPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建支付单
					Method:  http.MethodPost,
					Path:    "/payments",
					Handler: admincrmtradepayment.CreatePaymentHandler(serverCtx),
				},
				{
					// 查询支付单详情
					Method:  http.MethodGet,
					Path:    "/payments/:id",
					Handler: admincrmtradepayment.GetPaymentHandler(serverCtx),
				},
				{
					// 全量支付单
					Method:  http.MethodPut,
					Path:    "/payments/:id",
					Handler: admincrmtradepayment.PutPaymentHandler(serverCtx),
				},
				{
					// 增量支付单
					Method:  http.MethodPatch,
					Path:    "/payments/:id",
					Handler: admincrmtradepayment.PatchPaymentHandler(serverCtx),
				},
				{
					// 删除支付单
					Method:  http.MethodDelete,
					Path:    "/payments/:id",
					Handler: admincrmtradepayment.DeletePaymentHandler(serverCtx),
				},
				{
					// 查询支付单列表
					Method:  http.MethodGet,
					Path:    "/payments/page-list",
					Handler: admincrmtradepayment.ListPaymentsPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建代币产品
					Method:  http.MethodPost,
					Path:    "/products",
					Handler: admincrmtradetoken.CreateTokenProductHandler(serverCtx),
				},
				{
					// 查询代币产品详情
					Method:  http.MethodGet,
					Path:    "/products/:id",
					Handler: admincrmtradetoken.GetTokenProductHandler(serverCtx),
				},
				{
					// 全量代币产品
					Method:  http.MethodPut,
					Path:    "/products/:id",
					Handler: admincrmtradetoken.PutTokenProductHandler(serverCtx),
				},
				{
					// 增量代币产品
					Method:  http.MethodPatch,
					Path:    "/products/:id",
					Handler: admincrmtradetoken.PatchTokenProductHandler(serverCtx),
				},
				{
					// 删除代币产品
					Method:  http.MethodDelete,
					Path:    "/products/:id",
					Handler: admincrmtradetoken.DeleteTokenProductHandler(serverCtx),
				},
				{
					// 查询代币产品列表
					Method:  http.MethodGet,
					Path:    "/products/page-list",
					Handler: admincrmtradetoken.ListTokenProductsPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade/token"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 查询组织架构
					Method:  http.MethodGet,
					Path:    "/department-tree/:depId",
					Handler: admindepartment.GetDepartmentTreeHandler(serverCtx),
				},
				{
					// 创建新部门
					Method:  http.MethodPost,
					Path:    "/departments",
					Handler: admindepartment.CreateDepartmentHandler(serverCtx),
				},
				{
					// 获取单个部门详情
					Method:  http.MethodGet,
					Path:    "/departments/:id",
					Handler: admindepartment.GetDepartmentHandler(serverCtx),
				},
				{
					// 更新部门信息(可选更新)
					Method:  http.MethodPatch,
					Path:    "/departments/:id",
					Handler: admindepartment.PatchDepartmentHandler(serverCtx),
				},
				{
					// 删除部门
					Method:  http.MethodDelete,
					Path:    "/departments/:id",
					Handler: admindepartment.DeleteDepartmentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/department"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 获取字典项列表
					Method:  http.MethodGet,
					Path:    "/items",
					Handler: admindictionary.ListDictionaryItemsHandler(serverCtx),
				},
				{
					// 创建字典项
					Method:  http.MethodPost,
					Path:    "/items",
					Handler: admindictionary.CreateDictionaryItemHandler(serverCtx),
				},
				{
					// 获取字典项
					Method:  http.MethodGet,
					Path:    "/items/:type/:key",
					Handler: admindictionary.GetDictionaryItemHandler(serverCtx),
				},
				{
					// 更新字典项
					Method:  http.MethodPut,
					Path:    "/items/:type/:key",
					Handler: admindictionary.UpdateDictionaryItemHandler(serverCtx),
				},
				{
					// 删除字典项
					Method:  http.MethodDelete,
					Path:    "/items/:type/:key",
					Handler: admindictionary.DeleteDictionaryItemHandler(serverCtx),
				},
				{
					// 获取字典类型列表
					Method:  http.MethodGet,
					Path:    "/types",
					Handler: admindictionary.ListDictionaryTypesHandler(serverCtx),
				},
				{
					// 创建字典类型
					Method:  http.MethodPost,
					Path:    "/types",
					Handler: admindictionary.CreateDictionaryTypeHandler(serverCtx),
				},
				{
					// 获取字典类型
					Method:  http.MethodGet,
					Path:    "/types/:type",
					Handler: admindictionary.GetDictionaryTypeHandler(serverCtx),
				},
				{
					// 更新字典类型
					Method:  http.MethodPut,
					Path:    "/types/:type",
					Handler: admindictionary.UpdateDictionaryTypeHandler(serverCtx),
				},
				{
					// 删除字典类型
					Method:  http.MethodDelete,
					Path:    "/types/:type",
					Handler: admindictionary.DeleteDictionaryTypeHandler(serverCtx),
				},
				{
					// 获取字典类型列表
					Method:  http.MethodGet,
					Path:    "/types/page-list",
					Handler: admindictionary.ListDictionaryPageTypesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/dictionary"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创新类别
					Method:  http.MethodPost,
					Path:    "/categories",
					Handler: admininfoOrganizationcategory.CreateCategoryHandler(serverCtx),
				},
				{
					// 查询类别详情
					Method:  http.MethodGet,
					Path:    "/categories/:id",
					Handler: admininfoOrganizationcategory.GetCategoryHandler(serverCtx),
				},
				{
					// 修改类别
					Method:  http.MethodPut,
					Path:    "/categories/:id",
					Handler: admininfoOrganizationcategory.UpdateCategoryHandler(serverCtx),
				},
				{
					// 修改类别父级
					Method:  http.MethodPatch,
					Path:    "/categories/:id",
					Handler: admininfoOrganizationcategory.PatchCategoryHandler(serverCtx),
				},
				{
					// 删除类别
					Method:  http.MethodDelete,
					Path:    "/categories/:id",
					Handler: admininfoOrganizationcategory.DeleteCategoryHandler(serverCtx),
				},
				{
					// 查询类别列表
					Method:  http.MethodGet,
					Path:    "/category-tree",
					Handler: admininfoOrganizationcategory.ListCategoryTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/info-organization"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建媒资
					Method:  http.MethodPost,
					Path:    "/resources",
					Handler: adminmediaResource.CreateMediaResourceHandler(serverCtx),
				},
				{
					// 获取媒资详情
					Method:  http.MethodGet,
					Path:    "/resources/:id",
					Handler: adminmediaResource.GetMediaResourceHandler(serverCtx),
				},
				{
					// 删除媒资
					Method:  http.MethodDelete,
					Path:    "/resources/:id",
					Handler: adminmediaResource.DeleteMediaResourceHandler(serverCtx),
				},
				{
					// 创建媒资-Base64
					Method:  http.MethodPost,
					Path:    "/resources/base64",
					Handler: adminmediaResource.CreateMediaResourceByBase64Handler(serverCtx),
				},
				{
					// 查询媒资列表
					Method:  http.MethodGet,
					Path:    "/resources/page-list",
					Handler: adminmediaResource.ListMediaResourcesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/media"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 查询API列表
					Method:  http.MethodGet,
					Path:    "/api-list",
					Handler: adminpermission.ListAPIHandler(serverCtx),
				},
				{
					// 查询角色列表
					Method:  http.MethodGet,
					Path:    "/roles",
					Handler: adminpermission.ListRolesHandler(serverCtx),
				},
				{
					// 创建角色
					Method:  http.MethodPost,
					Path:    "/roles",
					Handler: adminpermission.CreateRoleHandler(serverCtx),
				},
				{
					// 获取角色详情
					Method:  http.MethodGet,
					Path:    "/roles/:roleCode",
					Handler: adminpermission.GetRoleHandler(serverCtx),
				},
				{
					// 更新角色详情
					Method:  http.MethodPatch,
					Path:    "/roles/:roleCode",
					Handler: adminpermission.PatchRoleHandler(serverCtx),
				},
				{
					// 为角色授予API权限
					Method:  http.MethodPost,
					Path:    "/roles/:roleCode/actions/set-permissions",
					Handler: adminpermission.SetRolePermissionsHandler(serverCtx),
				},
				{
					// 为角色分配用户
					Method:  http.MethodPost,
					Path:    "/roles/:roleCode/actions/set-users",
					Handler: adminpermission.SetRoleUsersHandler(serverCtx),
				},
				{
					// 获取角色的用户列表
					Method:  http.MethodGet,
					Path:    "/roles/:roleCode/users",
					Handler: adminpermission.GetRoleUsersHandler(serverCtx),
				},
				{
					// 为用户授予角色
					Method:  http.MethodPost,
					Path:    "/users/:userId/actions/set-roles",
					Handler: adminpermission.SetUserRolesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/permission"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建新职位
					Method:  http.MethodPost,
					Path:    "/positions",
					Handler: adminposition.CreatePositionHandler(serverCtx),
				},
				{
					// 获取职位列表
					Method:  http.MethodGet,
					Path:    "/positions",
					Handler: adminposition.ListPositionsHandler(serverCtx),
				},
				{
					// 更新职位信息(可选更新)
					Method:  http.MethodPatch,
					Path:    "/positions/:id",
					Handler: adminposition.PatchPositionHandler(serverCtx),
				},
				{
					// 删除职位
					Method:  http.MethodDelete,
					Path:    "/positions/:id",
					Handler: adminposition.DeletePositionHandler(serverCtx),
				},
				{
					// 获取职位详情
					Method:  http.MethodGet,
					Path:    "/positions/:id",
					Handler: adminposition.GetPositionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/position"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 查询菜单列表
					Method:  http.MethodGet,
					Path:    "/media/news/list",
					Handler: adminscrmwechatofficialAccountmedia.GetOAMediaNewsListHandler(serverCtx),
				},
				{
					// 创建菜单
					Method:  http.MethodPost,
					Path:    "/medias",
					Handler: adminscrmwechatofficialAccountmedia.CreateOAMediaHandler(serverCtx),
				},
				{
					// 请求菜单上传链接
					Method:  http.MethodGet,
					Path:    "/medias/:mediaId",
					Handler: adminscrmwechatofficialAccountmedia.GetOAMediaHandler(serverCtx),
				},
				{
					// 删除菜单
					Method:  http.MethodDelete,
					Path:    "/medias/:mediaId",
					Handler: adminscrmwechatofficialAccountmedia.DeleteOAMediaHandler(serverCtx),
				},
				{
					// 查询菜单列表
					Method:  http.MethodPost,
					Path:    "/medias/page-list",
					Handler: adminscrmwechatofficialAccountmedia.GetOAMediaListHandler(serverCtx),
				},
				{
					// 创建菜单
					Method:  http.MethodPost,
					Path:    "/medias/upload",
					Handler: adminscrmwechatofficialAccountmedia.UploadOAMediaHandler(serverCtx),
				},
				{
					// 根据媒体key获取媒体
					Method:  http.MethodGet,
					Path:    "/medias/video/:mediaId",
					Handler: adminscrmwechatofficialAccountmedia.GetOAMediaByVideoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/official-account"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创建菜单
					Method:  http.MethodPost,
					Path:    "/menus",
					Handler: adminscrmwechatofficialAccountmenu.CreateMenuHandler(serverCtx),
				},
				{
					// 删除菜单
					Method:  http.MethodDelete,
					Path:    "/menus",
					Handler: adminscrmwechatofficialAccountmenu.DeleteMenuHandler(serverCtx),
				},
				{
					// 查询菜单列表
					Method:  http.MethodGet,
					Path:    "/menus-tree",
					Handler: adminscrmwechatofficialAccountmenu.QueryMenusHandler(serverCtx),
				},
				{
					// 请求菜单上传链接
					Method:  http.MethodPost,
					Path:    "/menus/sync",
					Handler: adminscrmwechatofficialAccountmenu.SyncMenusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/official-account"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// App创建企业群
					Method:  http.MethodPost,
					Path:    "/group/create",
					Handler: adminscrmwechatwecomapp.CreateWeComAppGroupHandler(serverCtx),
				},
				{
					// App企业群列表/list
					Method:  http.MethodGet,
					Path:    "/group/list",
					Handler: adminscrmwechatwecomapp.ListWeComAppGroupHandler(serverCtx),
				},
				{
					// App企业群推送图文信息
					Method:  http.MethodPost,
					Path:    "/group/message/articles",
					Handler: adminscrmwechatwecomapp.SendWeComAppGroupArticleMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/app"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// App详情
					Method:  http.MethodGet,
					Path:    "/detail",
					Handler: adminscrmwechatwecomapp.DetailWeComAppHandler(serverCtx),
				},
				{
					// App列表/options
					Method:  http.MethodGet,
					Path:    "/options",
					Handler: adminscrmwechatwecomapp.ListWeComAppOptionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/app"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// App发送图文信息
					Method:  http.MethodPost,
					Path:    "/message/articles",
					Handler: adminscrmwechatwecomapp.SendWeComAppArticleMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/app"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 机器人发送图文信息
					Method:  http.MethodPost,
					Path:    "/message/articles",
					Handler: adminscrmwechatwecombot.BotWeComArticlesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/bot"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 查询渠道活码
					Method:  http.MethodGet,
					Path:    "/",
					Handler: adminscrmwechatwecomcontractway.GetContractWaysHandler(serverCtx),
				},
				{
					// 创建活码
					Method:  http.MethodPost,
					Path:    "/",
					Handler: adminscrmwechatwecomcontractway.CreateContractWayHandler(serverCtx),
				},
				{
					// 修改活码
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: adminscrmwechatwecomcontractway.UpdateContractWayHandler(serverCtx),
				},
				{
					// 删除活码
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: adminscrmwechatwecomcontractway.DeleteContractWayHandler(serverCtx),
				},
				{
					// 获取渠道活码分组树
					Method:  http.MethodGet,
					Path:    "/group-tree",
					Handler: adminscrmwechatwecomcontractway.GetContractWayGroupTreeHandler(serverCtx),
				},
				{
					// 查询渠道活码分组列表
					Method:  http.MethodGet,
					Path:    "/groups",
					Handler: adminscrmwechatwecomcontractway.GetContractWayGroupListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/contract-ways"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 查询客户详情列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: adminscrmwechatwecomcustomer.ListWeComCustomersHandler(serverCtx),
				},
				{
					// 查询客户详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: adminscrmwechatwecomcustomer.GetWeComCustomerHandler(serverCtx),
				},
				{
					// 修改客户信息
					Method:  http.MethodPatch,
					Path:    "/:id",
					Handler: adminscrmwechatwecomcustomer.PatchWeComCustomerHandler(serverCtx),
				},
				{
					// 同步客户
					Method:  http.MethodPost,
					Path:    "/actions/sync",
					Handler: adminscrmwechatwecomcustomer.SyncWeComCustomerHandler(serverCtx),
				},
				{
					// 所有客户列表/page
					Method:  http.MethodPost,
					Path:    "/page",
					Handler: adminscrmwechatwecomcustomer.ListWeComCustomerPageHandler(serverCtx),
				},
				{
					// 批量同步客户信息(根据员工ID同步/节流)
					Method:  http.MethodPost,
					Path:    "/sync",
					Handler: adminscrmwechatwecomcustomer.SyncWeComCustomerOptionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/customers"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 客户群列表/limit
					Method:  http.MethodPost,
					Path:    "/group/list",
					Handler: adminscrmwechatwecomcustomer.ListWeComCustomerGroupLimitHandler(serverCtx),
				},
				{
					// 客户群发信息
					Method:  http.MethodPost,
					Path:    "/group/message/template",
					Handler: adminscrmwechatwecomcustomer.SendWeComCustomerGroupMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/customers"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 部门列表/page
					Method:  http.MethodPost,
					Path:    "/departments/page",
					Handler: adminscrmwechatwecomorganization.ListWeComDepartmentPageHandler(serverCtx),
				},
				{
					// 查询组织架构
					Method:  http.MethodPost,
					Path:    "/departments/tree",
					Handler: adminscrmwechatwecomorganization.GetWeComDepartmentTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/organization"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 获取员工列表
					Method:  http.MethodPost,
					Path:    "/list",
					Handler: adminscrmwechatwecomorganization.ListWeComUserHandler(serverCtx),
				},
				{
					// 员工列表/page
					Method:  http.MethodPost,
					Path:    "/page",
					Handler: adminscrmwechatwecomorganization.ListWeComUserPageHandler(serverCtx),
				},
				{
					// 同步组织架构/department&user
					Method:  http.MethodGet,
					Path:    "/sync",
					Handler: adminscrmwechatwecomorganization.SyncWeComUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/organization/users"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 删除场景码
					Method:  http.MethodDelete,
					Path:    "/group/:qid",
					Handler: adminscrmwechatwecomqrcode.DeleteWeComQRCodeHandler(serverCtx),
				},
				{
					// 创建场景码
					Method:  http.MethodPost,
					Path:    "/group/create",
					Handler: adminscrmwechatwecomqrcode.CreateWeComQRCodeHandler(serverCtx),
				},
				{
					// 禁用场景码
					Method:  http.MethodPatch,
					Path:    "/group/disable/:qid",
					Handler: adminscrmwechatwecomqrcode.DisableWeComQRCodeHandler(serverCtx),
				},
				{
					// 启用场景码
					Method:  http.MethodPatch,
					Path:    "/group/enable/:qid",
					Handler: adminscrmwechatwecomqrcode.EnableWeComQRCodeHandler(serverCtx),
				},
				{
					// 场景码列表/page
					Method:  http.MethodPost,
					Path:    "/group/page",
					Handler: adminscrmwechatwecomqrcode.ListWeComQRCodePageHandler(serverCtx),
				},
				{
					// 更新场景码
					Method:  http.MethodPatch,
					Path:    "/group/update/:qid",
					Handler: adminscrmwechatwecomqrcode.UpdateWeComQRCodeHandler(serverCtx),
				},
				{
					// 下载场景码/upload
					Method:  http.MethodPatch,
					Path:    "/qrcode/:qid",
					Handler: adminscrmwechatwecomqrcode.UpdateActiveQRCodeLinkHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/qrcodes"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 微信素材库/page
					Method:  http.MethodPost,
					Path:    "/image/page",
					Handler: adminscrmwechatwecomresource.ListWeComImageHandler(serverCtx),
				},
				{
					// 上传图片到微信
					Method:  http.MethodPost,
					Path:    "/image/upload",
					Handler: adminscrmwechatwecomresource.CreateWeComImageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/resources"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 标签列表对象/key=>val
					Method:  http.MethodGet,
					Path:    "/corp/option",
					Handler: adminscrmwechatwecomtag.ListWeComTagOptionHandler(serverCtx),
				},
				{
					// 标签列表/page
					Method:  http.MethodPost,
					Path:    "/corp/page",
					Handler: adminscrmwechatwecomtag.ListWeComTagPageHandler(serverCtx),
				},
				{
					// 创建企业标签
					Method:  http.MethodPost,
					Path:    "/crop/create",
					Handler: adminscrmwechatwecomtag.CreateWeComCropTagHandler(serverCtx),
				},
				{
					// 批量删除企业标签
					Method:  http.MethodDelete,
					Path:    "/crop/delete",
					Handler: adminscrmwechatwecomtag.DeleteWeComCropTagHandler(serverCtx),
				},
				{
					// 编辑企业标签
					Method:  http.MethodPatch,
					Path:    "/crop/update",
					Handler: adminscrmwechatwecomtag.UpdateWeComCropTagHandler(serverCtx),
				},
				{
					// 编辑/删除客户标签
					Method:  http.MethodPost,
					Path:    "/customer/action",
					Handler: adminscrmwechatwecomtag.ActionWeComCustomerTagHandler(serverCtx),
				},
				{
					// 添加、删除标签组内的标签
					Method:  http.MethodPost,
					Path:    "/group/action",
					Handler: adminscrmwechatwecomtag.ActionWeComCropTagGroupHandler(serverCtx),
				},
				{
					// 标签组列表/option
					Method:  http.MethodGet,
					Path:    "/group/option",
					Handler: adminscrmwechatwecomtag.ListWeComTagGroupOptionHandler(serverCtx),
				},
				{
					// 标签组分页/page
					Method:  http.MethodPost,
					Path:    "/group/page",
					Handler: adminscrmwechatwecomtag.ListWeComTagGroupPageHandler(serverCtx),
				},
				{
					// 全量同步标签/sync
					Method:  http.MethodPut,
					Path:    "/sync",
					Handler: adminscrmwechatwecomtag.SyncWeComGroupTagHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/wechat/wecom/tags"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 创新标签
					Method:  http.MethodPost,
					Path:    "/",
					Handler: admintag.CreateTagHandler(serverCtx),
				},
				{
					// 查询标签详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: admintag.GetTagHandler(serverCtx),
				},
				{
					// 修改标签
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: admintag.UpdateTagHandler(serverCtx),
				},
				{
					// 修改标签父级
					Method:  http.MethodPatch,
					Path:    "/:id",
					Handler: admintag.PatchTagHandler(serverCtx),
				},
				{
					// 删除标签
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: admintag.DeleteTagHandler(serverCtx),
				},
				{
					// 查询标签列表
					Method:  http.MethodGet,
					Path:    "/tag-tree",
					Handler: admintag.ListTagTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/tags"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// List员工
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: adminuser.ListUsersHandler(serverCtx),
				},
				{
					// 创建员工
					Method:  http.MethodPost,
					Path:    "/users",
					Handler: adminuser.CreateUserHandler(serverCtx),
				},
				{
					// 查询员工
					Method:  http.MethodGet,
					Path:    "/users/:uuid",
					Handler: adminuser.GetUserHandler(serverCtx),
				},
				{
					// 编辑员工信息
					Method:  http.MethodPatch,
					Path:    "/users/:uuid",
					Handler: adminuser.UpdateUserHandler(serverCtx),
				},
				{
					// 删除员工
					Method:  http.MethodDelete,
					Path:    "/users/:uuid",
					Handler: adminuser.DeleteUserHandler(serverCtx),
				},
				{
					// 重设密码
					Method:  http.MethodPost,
					Path:    "/users/actions/reset-password",
					Handler: adminuser.ResetPasswordHandler(serverCtx),
				},
				{
					// 同步员工
					Method:  http.MethodPost,
					Path:    "/users/actions/sync",
					Handler: adminuser.SyncUsersHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserJWTAuth},
			[]rest.Route{
				{
					// 获取用户可见菜单
					Method:  http.MethodGet,
					Path:    "/menu-roles",
					Handler: adminuserinfo.GetMenuRolesHandler(serverCtx),
				},
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/user-info",
					Handler: adminuserinfo.GetUserInfoHandler(serverCtx),
				},
				{
					// 修改密码
					Method:  http.MethodPost,
					Path:    "/users/actions/modify-password",
					Handler: adminuserinfo.ModifyUserPasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/user-center"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/user-info",
					Handler: mpcrmcustomer.GetUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/customer"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 客户手机授权
				Method:  http.MethodPost,
				Path:    "/authByPhone",
				Handler: mpcrmcustomerauth.AuthByPhoneHandler(serverCtx),
			},
			{
				// 客户信息授权
				Method:  http.MethodPost,
				Path:    "/authByProfile",
				Handler: mpcrmcustomerauth.AuthByProfileHandler(serverCtx),
			},
			{
				// 微信小程序登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: mpcrmcustomerauth.LoginHandler(serverCtx),
			},
			{
				// 微信小程序Token验证
				Method:  http.MethodGet,
				Path:    "/validToken",
				Handler: mpcrmcustomerauth.ValidTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/mp/customer"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查询媒资列表
				Method:  http.MethodGet,
				Path:    "/medias/page-list",
				Handler: mpcrmmarketmedia.ListMediasPageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/mp/market"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 店铺列表
				Method:  http.MethodGet,
				Path:    "/stores/page-list",
				Handler: mpcrmmarketstore.ListStoresPageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/mp/market"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					// 查询会籍
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: mpcrmmembership.GetMembershipHandler(serverCtx),
				},
				{
					// 查询会籍
					Method:  http.MethodGet,
					Path:    "/customer",
					Handler: mpcrmmembership.GetCustomerMembershipHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/membership"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查询产品品类列表
				Method:  http.MethodGet,
				Path:    "/product-categories",
				Handler: mpcrmproduct.ListProductCategoriesHandler(serverCtx),
			},
			{
				// 查询产品品类树形表
				Method:  http.MethodGet,
				Path:    "/product-category-tree",
				Handler: mpcrmproduct.ListProductCategoryTreeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/mp/product"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查询产品详情
				Method:  http.MethodGet,
				Path:    "/products/:id",
				Handler: mpcrmproduct.GetProductHandler(serverCtx),
			},
			{
				// 产品列表
				Method:  http.MethodGet,
				Path:    "/products/page-list",
				Handler: mpcrmproduct.ListProductsPageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/mp/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth},
			[]rest.Route{
				{
					// 查询元匠详情
					Method:  http.MethodGet,
					Path:    "/artisans/:id",
					Handler: mpcrmproductartisan.GetArtisanHandler(serverCtx),
				},
				{
					// 查询元匠列表
					Method:  http.MethodGet,
					Path:    "/artisans/page-list",
					Handler: mpcrmproductartisan.ListArtisansPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/product"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查询产品统计详情
				Method:  http.MethodGet,
				Path:    "/product-statistics/:id",
				Handler: mpcrmproductproductstatistics.GetProductStatisticsHandler(serverCtx),
			},
			{
				// 查询产品统计列表
				Method:  http.MethodGet,
				Path:    "/product-statistics/page-list",
				Handler: mpcrmproductproductstatistics.ListProductStatisticsPageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/mp/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					// 创建账单地址
					Method:  http.MethodPost,
					Path:    "/billing",
					Handler: mpcrmtradeaddressbilling.CreateBillingAddressHandler(serverCtx),
				},
				{
					// 查询账单地址详情
					Method:  http.MethodGet,
					Path:    "/billing/:id",
					Handler: mpcrmtradeaddressbilling.GetBillingAddressHandler(serverCtx),
				},
				{
					// 更新账单地址
					Method:  http.MethodPut,
					Path:    "/billing/:id",
					Handler: mpcrmtradeaddressbilling.PutBillingAddressHandler(serverCtx),
				},
				{
					// 部分更新账单地址
					Method:  http.MethodPatch,
					Path:    "/billing/:id",
					Handler: mpcrmtradeaddressbilling.PatchBillingAddressHandler(serverCtx),
				},
				{
					// 删除账单地址
					Method:  http.MethodDelete,
					Path:    "/billing/:id",
					Handler: mpcrmtradeaddressbilling.DeleteBillingAddressHandler(serverCtx),
				},
				{
					// 查询账单地址列表
					Method:  http.MethodGet,
					Path:    "/billing/page-list",
					Handler: mpcrmtradeaddressbilling.ListBillingAddressesPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					// 创建订单发货地址
					Method:  http.MethodPost,
					Path:    "/delivery",
					Handler: mpcrmtradeaddressdelivery.CreateDeliveryAddressHandler(serverCtx),
				},
				{
					// 查询订单发货地址详情
					Method:  http.MethodGet,
					Path:    "/delivery/:id",
					Handler: mpcrmtradeaddressdelivery.GetDeliveryAddressHandler(serverCtx),
				},
				{
					// 更新订单发货地址
					Method:  http.MethodPut,
					Path:    "/delivery/:id",
					Handler: mpcrmtradeaddressdelivery.PutDeliveryAddressHandler(serverCtx),
				},
				{
					// 部分更新订单发货地址
					Method:  http.MethodPatch,
					Path:    "/delivery/:id",
					Handler: mpcrmtradeaddressdelivery.PatchDeliveryAddressHandler(serverCtx),
				},
				{
					// 删除订单发货地址
					Method:  http.MethodDelete,
					Path:    "/delivery/:id",
					Handler: mpcrmtradeaddressdelivery.DeleteDeliveryAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/delivery/page-list",
					Handler: mpcrmtradeaddressdelivery.ListDeliveryAddressesPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					// 创建收货地址
					Method:  http.MethodPost,
					Path:    "/shipping",
					Handler: mpcrmtradeaddressshipping.CreateShippingAddressHandler(serverCtx),
				},
				{
					// 查询收货地址详情
					Method:  http.MethodGet,
					Path:    "/shipping/:id",
					Handler: mpcrmtradeaddressshipping.GetShippingAddressHandler(serverCtx),
				},
				{
					// 更新收货地址
					Method:  http.MethodPut,
					Path:    "/shipping/:id",
					Handler: mpcrmtradeaddressshipping.PutShippingAddressHandler(serverCtx),
				},
				{
					// 部分更新收货地址
					Method:  http.MethodPatch,
					Path:    "/shipping/:id",
					Handler: mpcrmtradeaddressshipping.PatchShippingAddressHandler(serverCtx),
				},
				{
					// 删除收货地址
					Method:  http.MethodDelete,
					Path:    "/shipping/:id",
					Handler: mpcrmtradeaddressshipping.DeleteShippingAddressHandler(serverCtx),
				},
				{
					// 查询收货地址列表
					Method:  http.MethodGet,
					Path:    "/shipping/page-list",
					Handler: mpcrmtradeaddressshipping.ListShippingAddressesPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					// 获取购物车详情
					Method:  http.MethodGet,
					Path:    "/cart/:cartId",
					Handler: mpcrmtradecart.GetCartHandler(serverCtx),
				},
				{
					// 添加商品到购物车
					Method:  http.MethodPost,
					Path:    "/cart/items",
					Handler: mpcrmtradecart.AddToCartHandler(serverCtx),
				},
				{
					// 更新购物车商品数量
					Method:  http.MethodPut,
					Path:    "/cart/items/:itemId",
					Handler: mpcrmtradecart.UpdateCartItemQuantityHandler(serverCtx),
				},
				{
					// 删除购物车商品
					Method:  http.MethodDelete,
					Path:    "/cart/items/:itemId",
					Handler: mpcrmtradecart.RemoveCartItemHandler(serverCtx),
				},
				{
					// 清空购物车
					Method:  http.MethodDelete,
					Path:    "/cart/items/clear",
					Handler: mpcrmtradecart.ClearCartItemsHandler(serverCtx),
				},
				{
					// 查询购物车列表
					Method:  http.MethodGet,
					Path:    "/cart/items/page-list",
					Handler: mpcrmtradecart.ListCartItemsPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					// 查询订单详情
					Method:  http.MethodGet,
					Path:    "/orders/:id",
					Handler: mpcrmtradeorder.GetOrderHandler(serverCtx),
				},
				{
					// 取消订单
					Method:  http.MethodPut,
					Path:    "/orders/cancel/:id",
					Handler: mpcrmtradeorder.CancelOrderHandler(serverCtx),
				},
				{
					// 创建购物车订单
					Method:  http.MethodPost,
					Path:    "/orders/cart-items",
					Handler: mpcrmtradeorder.CreateOrderByCartItemsHandler(serverCtx),
				},
				{
					// 查询订单列表
					Method:  http.MethodGet,
					Path:    "/orders/page-list",
					Handler: mpcrmtradeorder.ListOrdersPageHandler(serverCtx),
				},
				{
					// 创建产品订单
					Method:  http.MethodPost,
					Path:    "/orders/products",
					Handler: mpcrmtradeorder.CreateOrderByProductsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					// 创建支付单
					Method:  http.MethodPost,
					Path:    "/payments",
					Handler: mpcrmtradepayment.CreatePaymentFromOrderHandler(serverCtx),
				},
				{
					// 查询支付单详情
					Method:  http.MethodGet,
					Path:    "/payments/:id",
					Handler: mpcrmtradepayment.GetPaymentHandler(serverCtx),
				},
				{
					// 修改支付单
					Method:  http.MethodPut,
					Path:    "/payments/:id",
					Handler: mpcrmtradepayment.UpdatePaymentHandler(serverCtx),
				},
				{
					// 查询支付单列表
					Method:  http.MethodGet,
					Path:    "/payments/page-list",
					Handler: mpcrmtradepayment.ListPaymentsPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					// 查询代币
					Method:  http.MethodGet,
					Path:    "/balance",
					Handler: mpcrmtradetoken.GetCustomerTokenBalanceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade/token"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取字典项列表
				Method:  http.MethodGet,
				Path:    "/items",
				Handler: mpdictionary.ListDictionaryItemsHandler(serverCtx),
			},
			{
				// 获取字典项
				Method:  http.MethodGet,
				Path:    "/items/:type/:key",
				Handler: mpdictionary.GetDictionaryItemHandler(serverCtx),
			},
			{
				// 获取字典类型
				Method:  http.MethodGet,
				Path:    "/types/:type",
				Handler: mpdictionary.GetDictionaryTypeHandler(serverCtx),
			},
			{
				// 获取字典类型列表
				Method:  http.MethodGet,
				Path:    "/types/page-list",
				Handler: mpdictionary.ListDictionaryPageTypesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/mp/dictionary"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WebCustomerJWTAuth},
			[]rest.Route{
				{
					// 获取字典项列表
					Method:  http.MethodGet,
					Path:    "/items",
					Handler: mpdictionary.ListDictionaryItemsHandler(serverCtx),
				},
				{
					// 获取字典项
					Method:  http.MethodGet,
					Path:    "/items/:type/:key",
					Handler: mpdictionary.GetDictionaryItemHandler(serverCtx),
				},
				{
					// 获取字典类型
					Method:  http.MethodGet,
					Path:    "/types/:type",
					Handler: mpdictionary.GetDictionaryTypeHandler(serverCtx),
				},
				{
					// 获取字典类型列表
					Method:  http.MethodGet,
					Path:    "/types/page-list",
					Handler: mpdictionary.ListDictionaryPageTypesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/web/dictionary"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创新类别
				Method:  http.MethodPost,
				Path:    "/categories",
				Handler: mpinfoOrganizationcategory.CreateCategoryHandler(serverCtx),
			},
			{
				// 查询类别详情
				Method:  http.MethodGet,
				Path:    "/categories/:id",
				Handler: mpinfoOrganizationcategory.GetCategoryHandler(serverCtx),
			},
			{
				// 修改类别
				Method:  http.MethodPut,
				Path:    "/categories/:id",
				Handler: mpinfoOrganizationcategory.UpdateCategoryHandler(serverCtx),
			},
			{
				// 修改类别父级
				Method:  http.MethodPatch,
				Path:    "/categories/:id",
				Handler: mpinfoOrganizationcategory.PatchCategoryHandler(serverCtx),
			},
			{
				// 删除类别
				Method:  http.MethodDelete,
				Path:    "/categories/:id",
				Handler: mpinfoOrganizationcategory.DeleteCategoryHandler(serverCtx),
			},
			{
				// 查询类别列表
				Method:  http.MethodGet,
				Path:    "/category-tree",
				Handler: mpinfoOrganizationcategory.ListCategoryTreeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/mp/info-organization"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OpenAPIJWTAuth, serverCtx.OpenAPIPlatformGet},
			[]rest.Route{
				{
					// Create a new echo message
					Method:  http.MethodPost,
					Path:    "/echo",
					Handler: openapi.CreateEchoHandler(serverCtx),
				},
				{
					// Get the version of the API
					Method:  http.MethodGet,
					Path:    "/version",
					Handler: openapi.GetVersionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/openapi/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Auth by platform
				Method:  http.MethodPost,
				Path:    "/",
				Handler: openapiauth.AuthPlatformHandler(serverCtx),
			},
		},
		rest.WithPrefix("/openapi/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OpenAPIJWTAuth},
			[]rest.Route{
				{
					// timeout api for provider demo
					Method:  http.MethodPost,
					Path:    "/echo-long-time",
					Handler: openapiproviderbrainx.EchoLongTimeHandler(serverCtx),
				},
				{
					// hello world api for provider demo
					Method:  http.MethodGet,
					Path:    "/hello-world",
					Handler: openapiproviderbrainx.HelloWorldHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/openapi/v1/provider/brainx"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 插件路由拉取
				Method:  http.MethodGet,
				Path:    "/plugin/v1/frontend-routes",
				Handler: plugin.ListPluginFrontendRoutesHandler(serverCtx),
			},
			{
				// 插件接口
				Method:  http.MethodPost,
				Path:    "/plugin/v1/plugins",
				Handler: plugin.RegisterPluginHandler(serverCtx),
			},
			{
				// 插件列表拉取
				Method:  http.MethodGet,
				Path:    "/plugin/v1/plugins",
				Handler: plugin.ListPluginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 健康检查接口
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: systemhealth.HealthCheckHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WebCustomerJWTAuth, serverCtx.WebCustomerGet},
			[]rest.Route{
				{
					// AI ChatBot Agent对话
					Method:  http.MethodPost,
					Path:    "/agent/chat",
					Handler: webaichatBot.AgentChatHandler(serverCtx),
				},
				{
					// AI ChatBot对话
					Method:  http.MethodPost,
					Path:    "/chat",
					Handler: webaichatBot.ChatHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sse/v1/web/chat-bot"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 微信Web登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: webcustomerauth.LoginHandler(serverCtx),
			},
			{
				// 客户手机注册
				Method:  http.MethodPost,
				Path:    "/registerByPhone",
				Handler: webcustomerauth.RegisterCustomerByPhoneHandler(serverCtx),
			},
			{
				// 客户手机注册，邀请码机制
				Method:  http.MethodPost,
				Path:    "/registerByPhone/invite/:code",
				Handler: webcustomerauth.RegisterCustomerByPhoneInInviteCodeHandler(serverCtx),
			},
			{
				// 客户手机注册，注册码机制
				Method:  http.MethodPost,
				Path:    "/registerByPhone/register/:code",
				Handler: webcustomerauth.RegisterCustomerByPhoneInRegisterCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/web/customer"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WebCustomerJWTAuth, serverCtx.WebCustomerGet},
			[]rest.Route{
				{
					// 客户信息更新
					Method:  http.MethodPost,
					Path:    "/updateCustomerProfile/:id",
					Handler: webcustomerauth.UpdateCustomerProfileHandler(serverCtx),
				},
				{
					// 获取用户信息
					Method:  http.MethodGet,
					Path:    "/user-info",
					Handler: webcustomerauth.GetUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/web/customer"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 客户手机授权
				Method:  http.MethodPost,
				Path:    "/oa/authByPhone",
				Handler: webcustomerauthoa.AuthByPhoneHandler(serverCtx),
			},
			{
				// 公众号客户信息授权
				Method:  http.MethodPost,
				Path:    "/oa/authByProfile",
				Handler: webcustomerauthoa.AuthByProfileHandler(serverCtx),
			},
			{
				// 微信公众号登录
				Method:  http.MethodPost,
				Path:    "/oa/login",
				Handler: webcustomerauthoa.OALoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/web/customer"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WebCustomerJWTAuth, serverCtx.WebCustomerGet},
			[]rest.Route{
				{
					// 创新类别
					Method:  http.MethodPost,
					Path:    "/categories",
					Handler: webinfoOrganizationcategory.CreateCategoryHandler(serverCtx),
				},
				{
					// 查询类别详情
					Method:  http.MethodGet,
					Path:    "/categories/:id",
					Handler: webinfoOrganizationcategory.GetCategoryHandler(serverCtx),
				},
				{
					// 修改类别
					Method:  http.MethodPut,
					Path:    "/categories/:id",
					Handler: webinfoOrganizationcategory.UpdateCategoryHandler(serverCtx),
				},
				{
					// 修改类别父级
					Method:  http.MethodPatch,
					Path:    "/categories/:id",
					Handler: webinfoOrganizationcategory.PatchCategoryHandler(serverCtx),
				},
				{
					// 删除类别
					Method:  http.MethodDelete,
					Path:    "/categories/:id",
					Handler: webinfoOrganizationcategory.DeleteCategoryHandler(serverCtx),
				},
				{
					// 查询类别列表
					Method:  http.MethodGet,
					Path:    "/category-tree",
					Handler: webinfoOrganizationcategory.ListCategoryTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/web/info-organization"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取场景落地页详情
				Method:  http.MethodGet,
				Path:    "/qrcode/detail/:qid",
				Handler: webscene.DetailQRCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/web/scene"),
	)
}
